[package]
name = "mlg"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
async-trait = "0.1.74"
serde = { version = "1.0.192", features = ["derive"] }
bincode = "1.3.3"
